### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by jniznan** [calmrat/metrique#105]
I propose using Travis. It should also support MongoDB.

http://about.travis-ci.org/docs/user/getting-started/

Numpy, pandas, tornado are using it.

**Comment by calmrat** [comment]
looks great; i've started playing with drone.io. Track your experience with travis here; i have no preference if we use one or the other, so let's just experiment a bit and decide after we've used them a bit more.

**Comment by calmrat** [comment]
could you also link here to your travis account? can i view the results?
