### ISSUE TITLE
set_cubes_path

### ISSUE THREAD

**Issue by jniznan** [calmrat/metrique#111]
It might be better if `set_cubes_path` set the path to cubes to be `metriquec.cube_name` and not just `cube_name`.

**Comment by calmrat** [comment]
perhaps this might be userful here:

http://docs.python.org/2/library/site.html

**Comment by calmrat** [comment]
hopefully this is fixed in https://github.com/drpoovilleorg/metrique/commit/f3d97b30c9ec1ecd3e39e570f8667aaafffc4d47
