### ISSUE TITLE
find interesting data sets to use as demo/docs

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#125]

**Comment by engineersamuel** [comment]
The million song dataset might be interesting to play around with: http://labrosa.ee.columbia.edu/millionsong/pages/getting-dataset 

Or any of the AWS public datasets: http://aws.amazon.com/datasets/

**Comment by calmrat** [comment]
wow, thanks! i like that the mill.song db is in HDF5; and amazon's selection of data is pretty broad; gotta be able to find something useful in there. Now... if only i can find time to explore! :)

**Comment by calmrat** [comment]
another interesting set to explore in a demo might be wikipedia
http://dumps.wikimedia.org/enwiki/latest/

**Comment by calmrat** [comment]
oh my. :) http://datahub.io/

**Comment by engineersamuel** [comment]
woaw, datahub.io is very intersting, exploring that right now.

**Comment by calmrat** [comment]
i've added the first simple example notebook; it's a start. closing.

https://github.com/drpoovilleorg/metrique/tree/master/notebooks
