### ISSUE TITLE
sped up gitrepo.commit parsing of 'stats' and several other similar fields

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#18]
https://github.com/drpoovilleorg/metrique/blob/master/metrique/client/cubes/gitrepo/commit.py#L136

'stats' is one property of a git commit that pythongit offers us. It shows +- lines per commit. But it's slow to extract. Without it enabled as a field in gitrepo.commit, we can process 900+ commits a second (which i think is also slow...); with it enabled, 30.

We need to make it faster.

**Comment by jniznan** [comment]
This is probably not a good long-term solution.
We might want to try to experiment with different python git libraries.
