### ISSUE TITLE
Enabled kerberos login ('basic')

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#19]
Wrap basic auth with kerberos auth handler for tornado 3.0
http://liftoff.github.io/GateOne/Developer/sso.html

I don't have a keytab yet to play with, so we'll only test this one with 'basic' kerberos auth and hope the key auth works like magic, as it should if the manual basic works.

**Comment by honzagrec** [comment]
I think http://tsennyipa.livejournal.com/9016.html using https://github.com/shuque/pykpass is an option.
But pykpass requires kerberos server to have this specific service registered (generated key) and copy of the keytab file, stored on metrique server, so no 'basic' kerberos auth

**Comment by calmrat** [comment]
interesting; i'll have to try to figure out how we could test it...

**Comment by calmrat** [comment]
resolved in 27cdf93b1d76a26ec6f3dd326b6606867216c35a

keytab support will come a bit later
