### ISSUE TITLE
add .removed() method for clients to remove objects from their collections

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#41]
wrap pymongo .remove()

**Comment by calmrat** [comment]
there should be an argument (?) for erasing across both warehouse and timeline.

**Comment by calmrat** [comment]
saving an update with no fields is a 'soft remove'

hard remove would be remove([_ids]) which actually calls pymongo.remove()

**Comment by jniznan** [comment]
If you save an object without some of the fields, those fields won't get erased, their values will be copied from the previous version. 

https://github.com/drpoovilleorg/metrique/blob/eb1e38c601a1b2632f67096eb23a8afe9d5e6c95/metrique/server/etl_api.py#L169-173

**Comment by calmrat** [comment]
the 'hard remove' is resolved in 1741a897945bdc34871361d256fc04b4d5d905e3

no 'soft remove' function implemented.
