### ISSUE TITLE
'full text' search? 

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#43]
on save_objects() index unique field token values per cube with map to _ids.

such that as metrique recieves an object like:

{
_id: 23523599
tweet: '#wow #metrique',
user: 'cward',
...
}

push workers fields and values and return back a set of unique (token, _id) tuples. The all those sets would be merged to (token, [_id, ...]).

@jniznan @wejnik   thoughts?

**Comment by calmrat** [comment]
just random thoughts...

**Comment by honzagrec** [comment]
To be honest, I don't fully understand what you mean

**Comment by calmrat** [comment]
haha; me neither. Anyway, we're not going to do this anytime soon. And probably better off just thinking in terms of deploying something like... http://lucene.apache.org/core/ (java, errr....)
