### ISSUE TITLE
disable/fix tornado.autoreload

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#72]
right now, with debug=True and changes to modules imported in/around tornado for tornado to  'reload' automatically. This puts the server into a broken state. eg, the metrique server itself doesn't restart properly. 

Either figure out a way to fix the reload so it doesn't leave the server in a broken state or disable to autoreload functionality without 'setting debug=False' in tornado webapp, if possible.

**Comment by calmrat** [comment]
this one is really annoying; i've actually tried to fsck with it already; tornado code has the autoreload module start no matter what, if debug=True is passed along to Application when creating a new tornado web application (see code in server/tornado.http._webapp())

Maybe.... we either patch tornado so we can pass in an argument to disabled autoreload (pretty easy, you get cool points for commiting to a _very_ popular project (tornado) but slower to get into the release (which is perfectly ok)

Or.... somehow we have to monkey patch the tornado web app instance to delete or disable the autoreload functionality... 

We DON"T want to simply not pass debug=True; we want debug turned on for other reasons that autoreload (logging, mostly).

Another option, perhaps, is to actualy make the autoreload hook functionality correctly stop and start (restart) the metrique-server instance... but at the moment when i try to server.stop() and server.start() i get an 'address already in use) error on start(). Which means the .stop() is NOT properly shutting down all instances and releases the resources (sockets) they were connected to.

**Comment by honzagrec** [comment]
If still actual, can you provide more info about:
- what version of metrique (metriqued) this happens on?
- by debug=True you mean first argument for metrique-server?
- by reloading you mean: metrique-server stop -> metrique-server start; metrique-server restart; both of those; none of those?
- broken state as metrique server itself won't start?

**Comment by calmrat** [comment]
i've reassigned to jniznan; do you still want this one? i didn't notice you had pinged! nice timing. 

Anyway, all versions; are afffected.

debug=true, yes, passed to metrique-server (or loaded from config, etc) which ultimately gets passed to tornado.handlers and used when creating a new web_app

Any time you change something that is touching tornado, the tornado IO loop restarts... but it fails to do so properly.  Just start metrique-server and then save metriqued/**init**.py for example (don't change anything, just save) and you'll see the server automatically restart... but if you try to interact with it, it fails to respond.

**Comment by calmrat** [comment]
maybe here's a hint; from http://www.tornadoweb.org/en/stable/web.html

"This is a convenience alias for creating an HTTPServer object and calling its listen method. Keyword arguments not supported by HTTPServer.listen are passed to the HTTPServer constructor. For advanced uses (e.g. multi-process mode), do not use this method; create an HTTPServer and call its TCPServer.bind/TCPServer.start methods directly."

**Comment by calmrat** [comment]
with the server restart 'killthemall' branch merged, does autoreload work now as it's supposed to with debug=True?

**Comment by calmrat** [comment]
@jniznan when you get a chance, now that the start/stop/restart stuff is working properly (or should be!!!) please try to get the autoreload to run properly when not disabled. If it's still not possible, file issues. Thanks!

**Comment by calmrat** [comment]
this is fixed; tornado now reloads properly when autoreload is enabled and a file is changed which affects the tornado object instance
