### ISSUE TITLE
cube.find() doesn't return cube_result object

### ISSUE THREAD

**Issue by honzagrec** [calmrat/metrique#74]
For example:

> > > res = bz_bug.find("reporter == 'jgrec@redhat.com'", "status")
> > > res.**class**
> > > <class 'metrique.client.result.Result'>

Should be BugResult.

To Test:
1)
   from metrique.client.cubes.utils import get_cube
   bz = get_cube("bz_bug")
   bz = bz()

2)
   from metrique import pyclient
   2a)
      pc = pyclient("bz_bug")
   2b)
      pc.find(cube="bz_bug")

3)
   from metrique.client.cubes import set_cube_path
   set_cube_path()  # is this needed?
   from bz_bug import Bug
   bz = Bug()

And then additional
- find
- fetch
  ...

**Comment by calmrat** [comment]
just to be clear, this is working in 

https://github.com/drpoovilleorg/metrique/tree/013a-setup-refactor

branch, which is set to become master (0.1.3.alpha) today

**Comment by calmrat** [comment]
In [1]: from metrique import pyclient
In [2]: b = pyclient(cube='bz_bug')
In [3]: b.find("product == 'Metrique'")
Out[3]: 
Empty BugResult          <-------------- correct type
Columns: []
Index: []

In [8]: from bz.bug import Bug
In [9]: b = Bug()
In [10]: b.find("product == 'Metrique'")
Out[10]: 
Empty BugResult          <-------------- correct type
Columns: []
Index: []
