### ISSUE TITLE
metriqued should have a non-mongo backend as default

### ISSUE THREAD

**Issue by calmrat** [calmrat/metrique#82]
mongo should not have to be running to use metriqued...

**Comment by calmrat** [comment]
eg? 
simple json?
http://try.redis.io/

**Comment by calmrat** [comment]
not as default; rather, as 'fallback'.  

Would be helpful for testing as well; no need to have a full mongo stack; just something which handles dictionaries...

**Comment by engineersamuel** [comment]
Let me know what you decide on with this, I'm also interested in a non-mongo fallback for Data Glue that requires no additional installs outside of say node or python.

**Comment by calmrat** [comment]
yea, happy to keep you up2date here; i haven't really thought it out too deeply; but something like pandas, pytable, discodb, might work? research and experiments still required.

**Comment by calmrat** [comment]
depends on what basic level of funcitonality that might be desired for a 'out of the box' 'low dependency' install without mongo; certain things are currently being tied to mongo like 'profile' related data... which will need to be refactored before mongo can be removed as a strict requirement, i suspect.

**Comment by calmrat** [comment]
pretty sure i'm going to go with pytables/hdfs for this

**Comment by calmrat** [comment]
see https://github.com/ContinuumIO/blaze
